name: CI CLI

on: [push, pull_request]

jobs:
  build:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t spotipy_image .
